FROM node:20-alpine AS build

WORKDIR /app
COPY package*.json ./
RUN npm install

COPY . .

ARG VITE_API_URL
ARG VITE_UPLOAD_URL
ARG VITE_API_TIMEOUT
ARG VITE_UPLOAD_TIMEOUT

ENV VITE_API_URL=$VITE_API_URL
ENV VITE_UPLOAD_URL=$VITE_UPLOAD_URL
ENV VITE_API_TIMEOUT=$VITE_API_TIMEOUT
ENV VITE_UPLOAD_TIMEOUT=$VITE_UPLOAD_TIMEOUT

RUN npm run build:prod

FROM nginx:alpine
COPY docker/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
